name: "Terraform CICD For GitHub Actions"
description: "Run Terraform plan and apply with detailed and formatted outputs"
branding:
  icon: "box"
  color: "purple"

inputs:
  terraform_version:
    description: "The version of terrafrom to install."
    default: 1.5.4
  terraform-working-dir:
    description: Path to the terraform working directory of your repository
    default: .

runs:
  using: "composite"
  steps:
    - name: Move to Terraform working directory
      shell: bash
      run: |
        cd ${{ inputs.terraform-working-dir }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false
        terraform_version: ${{ inputs.terraform_version }}

    - name: Terraform Init
      shell: bash
      run: |
        terraform init -upgrade
        terraform -v

    - name: Terraform Format
      shell: bash
      run: |
        terraform fmt -recursive -check

    - name: Terraform Validate
      shell: bash
      run: |
        terraform validate

    - name: Terraform Plan

      shell: bash
      run: |
        terraform plan --input=false --out=plan.out
