name: "Terraform CICD For GitHub Actions"
description: "Run Terraform plan and apply with detailed and formatted outputs"
branding:
  icon: "box"
  color: "purple"

inputs:
  terraform_version:
    description: "The version of terrafrom to install."
    default: 1.5.4

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false
        terraform_version: ${{ inputs.terraform_version }}

    - name: Terraform Init
      shell: bash
      run: |
        terraform init --terraform-non-interactive

    - name: Terraform Format
      shell: bash
      run: |
        terraform fmt -r --check

    - name: Terraform Validate
      shell: bash
      run: |
        terraform validate

    - name: Terraform Plan

      shell: bash
      run: |
        terraform plan --input=false --out=plan.out
